


CREATE TABLE IF NOT EXISTS USER_PAGES (
    user_id UUID REFERENCES USERS(user_id) ON DELETE CASCADE,
    doc_id INT REFERENCES DOCUMENTS(doc_id) ON DELETE CASCADE,
    current_page INT NOT NULL DEFAULT 1,
    last_viewed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, doc_id)
);

CREATE TABLE IF NOT EXISTS USER_LIKES (
    user_id UUID REFERENCES USERS(user_id) ON DELETE CASCADE,
    doc_id INT REFERENCES DOCUMENTS(doc_id) ON DELETE CASCADE,
    liked_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, doc_id)
);


SELECT * FROM USER_PAGES;